# Generated by Django 4.2.1 on 2023-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='The three-letter acronym for the cryptocurrency.', max_length=3, verbose_name='Acronym')),
                ('address', models.CharField(help_text='The valid address for the specified cryptocurrency.', max_length=100, verbose_name='Address')),
            ],
        ),
    ]
